### ISSUE TITLE
KeyError: x-csrf-token

### ISSUE THREAD

**Issue by lsvcode** [OriginalAlien/Roblox-Mass-Report#1]
Unfortunately, the tool does not work, I get this error when the program is meant to start reporting.
It's a shame as it seems very well put together and the only tool of its kind currently to be very recently updated.

`[>]Error: 'NoneType' object has no attribute 'attrs'
[>] Continuing...
Traceback (most recent call last):
  File "main.py", line 39, in <module>
    RB.report(victim, amount, reason, cooldown, reasonDescriptions[reason])
  File "/home/runner/Roblox-Mass-Report/RBXBan.py", line 138, in report
    "x-csrf-token": Utils.getXCsrf(cookie),
  File "/home/runner/Roblox-Mass-Report/RBXBan.py", line 43, in getXCsrf
    return xcsrfRequest.headers["x-csrf-token"]
  File "/home/runner/Roblox-Mass-Report/venv/lib/python3.8/site-packages/requests/structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'x-csrf-token'`

**Comment by OriginalAlien** [comment]
prolly invalid cookie
