### ISSUE TITLE
Error when more than 1 cookie in cookies.txt

### ISSUE THREAD

**Issue by markoapplettv** [OriginalAlien/Roblox-Mass-Report#16]
Hi, i keep getting this error whenever i have more than 1 cookie in the cookies.txt file. I also confirmed that these cookies aren't invalid.

Error message: Traceback (most recent call last):
  File "/home/USER/Desktop/Roblox-Mass-Report-main/main.py", line 30, in <module>
    RB.ban(victim, amount, reason, cooldown, reasons[reason]["comments"])
  File "/home/USER/Desktop/Roblox-Mass-Report-main/RBXBan.py", line 91, in ban
    xcsrfToken = xcsrfToken.headers["x-csrf-token"]
  File "/usr/lib/python3/dist-packages/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'x-csrf-token'

**Comment by TomerGamerTV** [comment]
did you run setup.bat?
